###
POST http://localhost:8080/mens
Content-Type: application/json

{
  "name":"민사",
  "age": 20,
  "gender": "male",
  "schoolId": 3
}

###
GET http://localhost:8080/mens
Content-Type: application/json

###
GET http://localhost:8080/mens/7
Content-Type: application/json

###
PUT http://localhost:8080/mens/3
Content-Type: application/json

{
  "name":"민삼",
  "gender": "male",
  "age": 21,
  "schoolId" : 3
}

###
DELETE http://localhost:8080/mens/2
Content-Type: application/json

###
POST http://localhost:8080/schools
Content-Type: application/json

{
  "major": "수학교육",
  "grade": 4
}

###
GET http://localhost:8080/schools
Content-Type: application/json

###
GET http://localhost:8080/schools/5
Content-Type: application/json

###
PUT http://localhost:8080/schools/4
Content-Type: application/json

{
  "major": "만화애니",
  "grade": 1
}

###
DELETE http://localhost:8080/schools/3
Content-Type: application/json

###
POST http://localhost:8080/majors
Content-Type: application/json

{
  "majorName": "스토리텔링의 이해",
  "majorUser": "강민영",
  "majorProfessor": "홍영미"
}

###
GET http://localhost:8080/majors
Content-Type: application/json

###
GET http://localhost:8080/majors/1
Content-Type: application/json

###
PUT http://localhost:8080/majors/1
Content-Type: application/json

{
  "majorName": "스토리텔링의 이해",
  "majorUser": "강민영",
  "majorProfessor": "홍영미"
}

###
DELETE http://localhost:8080/schools/3
Content-Type: application/json