###
POST http://localhost:8080/users
Content-Type: application/json

{
  "name":"민영",
  "age": 20,
  "gender": "male",
  "schoolId": 9,
  "majorId": 5
}

###
GET http://localhost:8080/users
Content-Type: application/json

###
GET http://localhost:8080/users/7
Content-Type: application/json

###
PUT http://localhost:8080/users/3
Content-Type: application/json

{
  "name":"민일",
  "age": 20,
  "gender": "male",
  "schoolId": 9,
  "majorId": 5
}

###
DELETE http://localhost:8080/users/2
Content-Type: application/json

###
POST http://localhost:8080/schools
Content-Type: application/json

{
  "schoolName": "내일배움"
}

###
GET http://localhost:8080/schools
Content-Type: application/json

###
GET http://localhost:8080/schools/5
Content-Type: application/json

###
PUT http://localhost:8080/schools/4
Content-Type: application/json

{
  "major": "만화애니",
  "grade": 1
}

###
DELETE http://localhost:8080/schools/8
Content-Type: application/json

###
POST http://localhost:8080/majors
Content-Type: application/json

{
  "majorName": "컴퓨터공학",
  "majorProfessor": "현석훈",
  "schoolId": 10
}

###
GET http://localhost:8080/majors
Content-Type: application/json

###
GET http://localhost:8080/majors/1
Content-Type: application/json

###
PUT http://localhost:8080/majors/1
Content-Type: application/json

{
  "majorName": "고전미술",
  "majorProfessor": "레오나르도"
}

###
DELETE http://localhost:8080/schools/3
Content-Type: application/json