###
POST http://localhost:8080/users
Content-Type: application/json

{
  "schoolId": 1,
  "majorId": 3,
  "name":"강민영",
  "age": 23,
  "gender": "female",
  "email": "email1234.email",
  "password": "password12"
}

###
POST http://localhost:8080/login
Content-Type: application/json

{
  "email": "email123.email",
  "password": "password1"
}

###
GET http://localhost:8080/test
Content-Type: application/json

###
GET http://localhost:8080/users
Content-Type: application/json

###
GET http://localhost:8080/users/9
Content-Type: application/json

###
PUT http://localhost:8080/users/18
Content-Type: application/json

{
  "schoolId": 1,
  "majorId": 2,
  "name":"민영십육",
  "age": 20,
  "gender": "male"
}

###
DELETE http://localhost:8080/users/8
Content-Type: application/json

###
POST http://localhost:8080/schools
Content-Type: application/json

{
  "schoolName": "와삼대학"
}

###
GET http://localhost:8080/schools
Content-Type: application/json

###
GET http://localhost:8080/schools/2
Content-Type: application/json

###
PUT http://localhost:8080/schools/6
Content-Type: application/json

{
  "schoolName": "우리대학"
}

###
DELETE http://localhost:8080/schools/7
Content-Type: application/json

###
POST http://localhost:8080/majors
Content-Type: application/json

{
  "majorName": "물리학",
  "majorProfessor": "일이삼"
}

###
GET http://localhost:8080/majors
Content-Type: application/json

###
GET http://localhost:8080/majors/2
Content-Type: application/json

###
PUT http://localhost:8080/majors/6
Content-Type: application/json

{
  "majorName": "물리학",
  "majorProfessor": "아이작 뉴턴"
}

###
DELETE http://localhost:8080/majors/6
Content-Type: application/json